- name: Install nginx and start
  hosts: frontend
  become: yes
  tasks:
    - name: Install nginx
      ansible.builtin.dnf:
        name: nginx
        state: present
      when: ansible_os_family == "RedHat"
    - name: Install nginx
      ansible.builtin.apt:
        name: nginx
        state: present
      when: ansible_os_family == "Debian"
    - name: Enable service
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
