- name: Looping through item to install
  hosts: frontend
  become: yes
  tasks:
    - name: install
      ansible.builtin.dnf:
        name: '{{ item }}'
        state: present
      # ansible.builtin.debug:          Ansible tasks allow one module per task name
      #   msg: '{{ item }} is installed'
      loop:
        - nginx
        - httpd
        - mysql
